InseeFr/sugoi-ui

src/api/remote/remote.tsx
Signed-off-by: Cédric Couralet <cedric.couralet@insee.fr>
=> Fix realms Uri

src/redux/reducers/user.ts
Signed-off-by: Cédric Couralet <cedric.couralet@insee.fr>
=> Fix removal of access_token from store

.gitignore, src/components/commons/dataViewer/dataviewer.tsx, src/components/realmHome/index.tsx, src/hooks/technics/useForms.tsx, src/routes/routes.tsx
Signed-off-by: Cédric Couralet <cedric.couralet@insee.fr>
=> Fix #54: Choose correct component for user creation and organization creation

docs/configuration.md, docs/develop.md, docs/field.md, package.json, src/components/commons/formular/fields/habilitationsFieldInfo/habilitationFieldInfoPopup.tsx, src/components/commons/formular/fields/habilitationsFieldInfo/index.tsx, src/model/api/habilitation.tsx, src/model/api/user.tsx, yarn.lock
=> update dependencies and add a few doc

package.json, public/locales/fr/translation.json, src/api/index.tsx, src/api/remote/applicationApi.tsx, src/components/commons/header/all-icon-button/language-button.tsx, src/components/commons/popButton/Dialog.tsx, src/components/commons/searchResults/index.tsx, src/components/commons/sider/sider-body.tsx, src/components/detailsApplication/ManageButtonGroup/content/addUser.tsx, src/components/detailsApplication/ManageButtonGroup/content/createGroup.tsx, src/components/detailsApplication/ManageButtonGroup/content/groupSelector.tsx, src/components/detailsApplication/ManageButtonGroup/content/index.tsx, src/components/detailsApplication/ManageButtonGroup/content/listUser.tsx, src/components/detailsApplication/ManageButtonGroup/index.tsx, src/components/detailsApplication/chip/index.tsx, src/components/detailsApplication/index.tsx, src/components/realmHome/index.tsx, src/components/searchApplication/button-create-app.tsx, src/components/searchApplication/index.tsx, src/hooks/applications/useGetApplication.tsx, src/hooks/applications/useGetApplications.tsx, src/hooks/applications/usePostApplication.tsx, src/hooks/applications/usePutApplication.tsx, src/model/api/application.tsx, src/model/api/attributes.tsx, src/model/js/searchRequestUser.tsx, src/routes/routes.tsx, yarn.lock
=> add applications parts

src/api/remote/applicationApi.tsx, src/api/remote/credentialApi.tsx, src/api/remote/groupApi.tsx, src/api/remote/organizationApi.tsx, src/api/remote/userApi.tsx
=> use new endpoints

src/api/index.tsx, src/api/remote/groupApi.tsx, src/api/remote/userApi.tsx, src/components/commons/searchResults/index.tsx, src/components/detailsApplication/ButtonManageGroup/addUser.tsx, src/components/detailsApplication/ButtonManageGroup/index.tsx, src/components/detailsApplication/index.tsx, src/components/searchOrganizations/index.tsx, src/components/searchUsers/index.tsx, src/hooks/group/useAddUserToGroup.tsx, src/hooks/group/useDeleteUserFromGroup.tsx, src/hooks/group/useGetGroup.tsx, tsconfig.json
=> use new endpoint to manage group

src/components/detailsApplication/ButtonCreateGroup/index.tsx, src/components/detailsApplication/index.tsx
=> Resolve [123] Show that the groupname must be suffix by the appName

src/components/commons/formular/fields/groupsFieldInfo/index.tsx, src/hooks/realm/useRealmConfig/fieldToDisplay/FieldToDisplayConfigUser.tsx
=> Resolve [117] Change the hability to manage group (in user) to readonly

src/api/remote/organizationApi.tsx
=> Fix [128] :bug: Single organization is not taken from the good endpoint

public/locales/fr/translation.json
change title to Service unifié de Gestion des openldaps de l'insee
=> fix [116] change title

src/api/index.tsx, src/api/remote/applicationApi.tsx, src/components/detailsApplication/index.tsx, src/hooks/applications/useDeleteApplication.tsx
=> Resolve [125] Add delete button on app view

src/api/remote/userApi.tsx, src/components/searchUsers/index.tsx, src/hooks/user/useGetUsers.tsx, src/model/js/searchRequestUser.tsx
=> Fix [130] Add search by mail

public/locales/fr/translation.json, src/api/remote/organizationApi.tsx, src/components/searchOrganizations/index.tsx, src/hooks/organization/useGetOrganizations.tsx, src/model/js/searchRequestOrganization.tsx
linked to https://github.com/InseeFrLab/sugoi-api/pull/305
=> Add search by identifiant and mail on organizations page

package.json
=> Prepare version 0.2.0

src/configuration/utils.tsx
=> remove: access-control-origin-header

public/locales/fr/translation.json, src/components/app.tsx, src/components/commons/header/all-icon-button/grouped-buttons.tsx, src/components/commons/header/all-icon-button/notif-button.tsx, src/components/notifications/index.tsx, src/configuration/axios-configuration.tsx, src/configuration/store-configuration.ts, src/hooks/technics/useLocalStorage.tsx, src/redux/actions/app.ts, src/redux/actions/notif.ts, src/redux/reducers/app.ts, src/redux/reducers/notifs.ts
=> [ENH] ✨Improve notification management

package.json
=> [REL] 🚀 prepare version 0.3.0

public/locales/en/translation.json, public/locales/fr/translation.json, src/components/commons/formular/fields/habilitationsFieldInfo/index.tsx, src/components/notifications/index.tsx, src/components/notifications/textNotification.tsx, src/configuration/axios-configuration.tsx, src/index.tsx
Signed-off-by: Clément Dufaure <clement.dufaure@insee.fr>
=> [ENH] :sparkles: improve notification labels and habilitation display

public/locales/fr/translation.json, src/components/home/landingpage/landingpage.tsx
=> [ENH] ✨ Change button c'est parti

src/hooks/realm/useRealmConfig/fieldToDisplay/FieldToDisplayConfigUser.tsx
=> [ENH] :sparkles: add insee_timbre on user view

.github/workflows/release.yml
=> [ENH] ✨ improve ci on release 

public/locales/fr/translation.json, src/components/commons/sider/sider-body.tsx
=> [ENH] :sparkles: change sider text

.github/workflows/release.yml
We have to disable `yarn version` commiting to do it manually
Signed-off-by: Cédric Couralet <cedric.couralet@insee.fr>
=> [META] 📇 Signoff commit message when releasing (#181)

public/locales/fr/translation.json, src/api/index.tsx, src/api/remote/index.tsx, src/api/remote/whoamiApi.tsx, src/components/home/right-card.tsx, src/hooks/whoami/index.tsx, src/model/api/whoami.tsx
=> [ENH] ✨ use whoami endpoint

public/configuration.json, public/locales/fr/translation.json, src/components/commons/header/all-icon-button/grouped-buttons.tsx, src/components/commons/header/all-icon-button/help-button.tsx, src/hooks/technics/useConfigFile.tsx
=> [ENH] ✨ add documentation link on top of page

src/hooks/realm/useRealmConfig/fieldToDisplay/FieldToDisplayConfigUser.tsx
Signed-off-by: Clément Dufaure <clement.dufaure@insee.fr>
=> [TYPO] restore common name

public/locales/fr/translation.json, src/api/index.ts, src/api/remote/credentialApi.tsx, src/components/commons/sendUsernamePopup/index.tsx, src/hooks/credential/useSendIdentifiant.tsx
Signed-off-by: Clément Dufaure <clement.dufaure@insee.fr>
=> [FIX] Fix send login button

src/components/commons/sider/sider-body.tsx, src/components/commons/sider/sider-permanent.tsx, src/components/commons/sider/sider-temporary.tsx, src/model/api/realm.ts
=> [ENH] :sparkles: Hide unconfigured functionnality (#213)

src/api/fake/userFake.ts, src/api/remote/exportApi.ts, src/api/remote/userApi.ts, src/components/detailsApplication/ButtonManageGroup/addUser.tsx, src/components/searchUsers/index.tsx, src/hooks/user/useGetUsers.ts, src/model/js/searchRequestUser.tsx
=> [BUG] :bug: User search param is CommonName instead of nomCommun

src/hooks/realm/useRealmConfig.tsx, src/model/api/mapping.ts
=> [BUG] :bug: Fix uiOrganizationMapping not taken into account

package.json, src/components/commons/description/index.tsx, src/components/commons/sider/sider-body.tsx, src/components/settings/settings.tsx, src/hooks/realm/useGetRealm.tsx, src/hooks/realm/useGetRealms.tsx, src/hooks/realm/useRealmConfig.tsx, src/redux/actions/app.ts, src/redux/reducers/app.ts, yarn.lock
=> Get realms from redux store

.github/workflows/check-commits.yml
=> [META] 📇 Add commit message check on PR

public/locales/fr/translation.json, src/components/commons/confirmationPopUp/index.tsx, src/components/commons/loadingButton/index.tsx, src/components/detailsApplication/ButtonDeleteGroup/index.tsx, src/components/detailsApplication/ButtonManageGroup/genericButtonManageGroup/index.tsx, src/components/detailsApplication/ButtonManageGroup/index.tsx, src/components/detailsApplication/index.tsx, src/components/detailsOrganization/index.tsx, src/components/detailsUser/index.tsx, src/hooks/group/useGetGroupManager.tsx
=> [ENH] :sparkles: ask before to delete

src/components/commons/header/all-icon-button/theme-button.tsx, src/hooks/technics/useLocalStorage.tsx, src/redux/reducers/app.ts, src/utils/functions.ts
=> [BUG] :bug: fix nightmode not default

entrypoint.sh, public/configuration.json, public/locales/fr/translation.json, src/api/index.ts, src/api/remote/credentialApi.ts, src/components/commons/resetPasswordPopup/index.tsx, src/components/commons/resetPasswordPopup/resetPasswordPopupContent.tsx, src/components/commons/sendUsernamePopup/index.tsx, src/components/commons/sendUsernamePopup/sendPopupContent.tsx, src/hooks/credential/useResetPassword.tsx, src/hooks/credential/useSendIdentifiant.tsx, src/model/api/TemplateProperties.ts, src/model/api/passwordChangeRequest.ts
=> Follow API changes for CredentialsController

src/lib/hooks/technics/useForms.tsx
=> [BUG] :bug: The first character hit in a form should not be ignored

src/components/shared/resetPasswordPopup/index.tsx, src/components/shared/resetPasswordPopup/resetPasswordPopupContent.tsx, src/lib/api/index.ts, src/lib/api/remote/credentialApi.ts, src/lib/hooks/credential/useResetPassword.tsx
(#266)
Signed-off-by: Emmanuel Barrios <emmanuel.barrios@insee.fr>
=> [ENH] ✨ Add a toggle to ask for password reset on password reinit

public/locales/fr/translation.json, src/components/pages/createOrganization/index.tsx, src/components/pages/createUser/index.tsx, src/components/pages/detailsApplication/index.tsx, src/components/pages/detailsOrganization/index.tsx, src/components/pages/detailsUser/index.tsx, src/components/pages/home/home.tsx, src/components/pages/realmHome/index.tsx, src/components/pages/searchApplications/index.tsx, src/components/pages/searchOrganizations/index.tsx, src/components/pages/searchUsers/index.tsx, src/components/pages/settings/index.tsx
=> [ACC] ✨ Each page should have a different title

public/locales/en/translation.json, public/locales/fr/translation.json
Signed-off-by: Emmanuel Barrios <emmanuel.barrios@insee.fr>
closes #83
=> 👽 Translate in english (#83)

package.json
Signed-off-by: Mehdi Maaref <mehdi.maaref@insee.fr>
=>  [UP] ⬆️ Bump react from 17.0.2 to 18.0.0 

src/components/pages/searchUsers/index.tsx, src/components/shared/formular/fields/habilitationsFieldInfo/index.tsx, src/lib/model/api/user.ts
=> [BUG] :bug: Fix habilitations and groups are optional

.eslintrc, package.json, public/locales/fr/translation.json, src/components/pages/searchOrganizations/index.tsx, src/components/pages/searchUsers/index.tsx, src/components/shared/searchFormular/index.tsx, src/lib/api/index.ts, src/lib/api/remote/organizationApi.ts, src/lib/hooks/organization/useGetOrganizations.tsx, src/lib/hooks/technics/useForms.tsx, yarn.lock
=> [ENH] :sparkles: add global research

src/lib/hooks/technics/useForms.tsx, src/lib/utils/clone.ts
=> [BUG] :bug: repair reset functionnality in hook useform

public/locales/en/translation.json, public/locales/fr/translation.json, src/components/pages/home/right-card.tsx, src/components/pages/searchApplications/application_card.tsx, src/components/pages/searchApplications/applications_favorite_list.tsx, src/components/pages/searchApplications/applications_list.tsx, src/components/pages/searchApplications/applications_viewer.tsx, src/components/pages/searchApplications/button-create-app.tsx, src/components/pages/searchApplications/index.tsx, src/components/pages/searchOrganizations/index.tsx, src/components/pages/searchUsers/index.tsx, src/components/shared/searchResults/index.tsx, src/lib/api/index.ts, src/lib/api/remote/applicationApi.ts, src/lib/hooks/applications/useGetApplications.tsx, src/lib/hooks/whoami/index.tsx, src/lib/model/api/attributesApplication.ts
=> [ENH] :sparkles: new page applicationsSearch

src/components/pages/detailsApplication/index.tsx, src/components/pages/searchApplications/applications_viewer.tsx, src/components/pages/searchApplications/index.tsx, src/components/shared/searchResults/index.tsx
Signed-off-by: ahliit <cecile.chemin@insee.fr>
=> [BUG] :bug: Fix redirect on user details not working

public/locales/fr/translation.json, src/components/pages/detailsUser/index.tsx, src/components/pages/realmHome/favorite_button.tsx, src/components/pages/realmHome/index.tsx, src/components/shared/jsonEditor/index.tsx, src/components/shared/notifications/textNotification.tsx, src/components/shared/sider/sider-body.tsx, src/lib/api/index.ts, src/lib/redux/actions/app.ts, src/lib/redux/reducers/app.ts, src/lib/utils/form_utils.ts, src/lib/utils/functions.ts
=> [ENH] :sparkles: add realm to favorite

src/components/shared/formular/fields/manageGpgKey/index.tsx
=> [BUG] :bug: Fix gpg key loading

package.json, src/components/app/app.tsx, src/components/pages/createOrganization/index.tsx, src/components/pages/createUser/index.tsx, src/components/pages/detailsApplication/chip/index.tsx, src/components/pages/detailsApplication/index.tsx, src/components/pages/detailsOrganization/index.tsx, src/components/pages/detailsUser/index.tsx, src/components/pages/home/landingpage/landingpage.tsx, src/components/pages/realmHome/index.tsx, src/components/pages/searchApplications/index.tsx, src/components/pages/searchOrganizations/index.tsx, src/components/pages/searchUsers/index.tsx, src/components/routes/routes.tsx, src/components/shared/breadcrumbs/breadcrumbs.tsx, src/components/shared/formular/fields/groupsFieldInfo/index.tsx, src/components/shared/formular/fields/habilitationsFieldInfo/index.tsx, src/components/shared/formular/fields/manageCertificateField/index.tsx, src/components/shared/formular/fields/manageGpgKey/index.tsx, src/components/shared/formular/fields/simpleAppManageAttributes/index.tsx, src/components/shared/header/all-icon-button/login-button.tsx, src/components/shared/resetPasswordPopup/index.tsx, src/components/shared/sendUsernamePopup/index.tsx, src/components/shared/sider/sider-body.tsx, yarn.lock
=> [UP] :arrow_up: Bump react-router-dom to 6.3.0
